### ISSUE TITLE
landroid-card error

### ISSUE THREAD

**Issue by PaulMalmqvist** [Barma-lej/landroid-card#3]
I have installed your landroid-card.js according to your instructions.
But I get this error in the logs:
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 3:20:14 PM (1 occurrences)
Last logged: 3:20:14 PM

https://x.x.x:8123/local/landroid-card.js:1:19759 Uncaught ReferenceError: regeneratorRuntime is not defined

Can you help me with this?

Regards
Paul Malmqvist

**Comment by vanstolyarov** [comment]
Exactly the same for me
Steps:
- i have a working landroid integration
- added landroid-card repo in HACS
<img width="452" alt="Снимок экрана 2022-07-05 в 11 39 09" src="https://user-images.githubusercontent.com/26839184/177287913-9b914fb5-ef88-42f8-9ca7-2f1a85a70941.png">
- addes Landroid Card in HACS
<img width="499" alt="Снимок экрана 2022-07-05 в 11 38 55" src="https://user-images.githubusercontent.com/26839184/177287911-c4fe68d3-97b4-4853-bab1-cf338e98a613.png">
- added resource to HA configuration
<img width="373" alt="Снимок экрана 2022-07-05 в 11 38 39" src="https://user-images.githubusercontent.com/26839184/177287908-8d0da0a2-3e2f-453b-93b1-844abaed3ea9.png">
- added card in lovelace.yaml
<img width="273" alt="Снимок экрана 2022-07-05 в 11 48 01" src="https://user-images.githubusercontent.com/26839184/177288903-7550d19e-27b3-4866-9d1e-e5815e0e9eb2.png">

Restarted HA, after that:
<img width="288" alt="Снимок экрана 2022-07-05 в 11 38 16" src="https://user-images.githubusercontent.com/26839184/177287895-40d619af-cf39-40e3-9437-27cee686411f.png">

Error in dev console
<img width="1421" alt="Снимок экрана 2022-07-05 в 11 38 24" src="https://user-images.githubusercontent.com/26839184/177287904-74f56cf0-fcda-41f9-ac58-eddf2a1065e3.png">

Home Assistant Core 2022.6.7
Google Chrome  103.0.5060.114 (arm64)

**Comment by wimpie007** [comment]
same here:
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 11:53:00 AM (4 occurrences)
Last logged: 11:55:47 AM

http://x.x.x.x:8123/local/landroid-card.js:1:19759 Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by Barma-lej** [comment]
Fixed with release [0.1.3](https://github.com/Barma-lej/landroid-card/releases/tag/0.1.3)

**Comment by wimpie007** [comment]
still a problem:
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 2:46:14 PM (4 occurrences)
Last logged: 2:55:02 PM

http://192.168.1.155:8123/local/landroid-card.js:1:19759 Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by Barma-lej** [comment]
Which version of landroid-card do you have in HACS?
![Screenshot 2022-07-06 160945](https://user-images.githubusercontent.com/34010886/177570603-f3754329-cf9c-4dcf-924c-a26572e35d0e.jpg)

**Comment by wimpie007** [comment]
heuh. 
![image](https://user-images.githubusercontent.com/33153228/177571945-52891721-1509-49db-9748-a4a85a0d0213.png)

It is not in hacs according to your docs?

**Comment by vanstolyarov** [comment]
> still a problem: Logger: frontend.js.latest.202206010 Source: components/system_log/**init**.py:190 First occurred: 2:46:14 PM (4 occurrences) Last logged: 2:55:02 PM
> 
> http://192.168.1.155:8123/local/landroid-card.js:1:19759 Uncaught ReferenceError: regeneratorRuntime is not defined

I still have the same error with 0.1.3 from HACS
But it works great in Safari or in Chrome private browsing
Looks like cache problem

**Comment by wimpie007** [comment]
Through HACS (custom repo) it works!
Thanks!
![image](https://user-images.githubusercontent.com/33153228/177574559-d20f6afa-4b0d-4d69-b44d-8c72d24eb76e.png)

**Comment by Barma-lej** [comment]
You can add this repository to HACS manualy.
If you just download and copy landroid-card.js than you have to clean browser cache.
1. Open home assistant in your favorite browser, e.g. Google Chrome
2. Go to view wit Landroid Card
3. Press right mouse button and select Inspect. Or press Command+Option+C (Mac) or Control+Shift+C (Windows, Linux, ChromeOS)
4. Press right mouse button on Update button in browser and select "Cache ... bla bla"
![Unbenannt](https://user-images.githubusercontent.com/34010886/177575256-ba1b8e9b-a6f6-49e2-b76c-94c3864ef349.jpg)

**Comment by Barma-lej** [comment]
> It is not in hacs according to your docs?

[Added HACS manual method install](https://github.com/Barma-lej/landroid-card/commit/5c6c628249a789261ffd965946fc481c8df796f3) to README.MD
